site_name: OBO Semantic Engineering Training
theme:
  name: material
  icon:
    edit: material/pencil 
  features:
    - content.action.edit
    #- navigation.tabs
    #- toc.integrate
    #- navigation.sections
    #- navigation.top
    - search.suggest
    - search.highlight
    #- content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - About the course: index.md
  - Getting started with learning: getting-started.md
  - Overview of lessons and tutorials: overview.md
  - Contribute to the course: contributing.md
  - Courses:
      - ICBO 2024 Tutorial: courses/icbo2024.md
      - ICBO 2023 Tutorial: courses/icbo2023.md
      - ICBO 2022 Tutorial: courses/icbo2022.md
      - ICBO 2021 Tutorial: courses/icbo2021.md
      - Monarch Ontology Training: courses/monarch-obo-training.md
      - Ontology Summit 2023: courses/ontology-summit-2023.md
  - Pathways:
      - What is a pathway?: pathways/pathways.md
      - Early Career Data Scientist: pathways/early-career-data-scientist.md
      - Ontology Curator: pathways/ontology-curator.md
      - Ontology Curator GO-style: pathways/ontology-curator-go-style.md
      - Ontology Curator OBI-style: pathways/ontology-curator-obi-style.md
      - Ontology Engineer/Developer: pathways/ontology-engineer.md
      - Ontology Contributor: pathways/ontology-contributor.md
      - AI-powered semantic engineer: pathways/ai-powered-semantic-engineer.md
  - Lessons:
      - Contributing to OBO ontologies: lesson/contributing-to-obo-ontologies.md
      - Ontology Pipelines with ROBOT: lesson/ontology-pipelines.md
      - Project Ontology Development: tutorial/project-ontology-development.md
      - Analysing Linked Data: lesson/analysing-linked-data.md
      - Automating Ontology Workflows: lesson/automating-ontology-workflows.md
      - Developing an OBO Ontology: lesson/developing-an-obo-ontology.md
      - Ontology Design: lesson/ontology-design.md
      - Templates for OBO ontologies: lesson/templates-for-obo.md
      - Ontology Fundamentals: lesson/ontology-fundamentals.md
      - Modelling with Object Properties: lesson/modelling-with-object-properties.md
      - Ontology Term Use: lesson/ontology-term-use.md
      - RDF Fundamentals: lesson/rdf.md
      - Semantic Entity Matching: lesson/entity-matching.md
      - Disease and Phenotype Ontologies: lesson/using-disease-and-phenotype-ontologies.md
      - Basic concepts of phenotype data and ontologies: lesson/phenotype-data.md
      - Hacking the OBOOK: lesson/hackathon.md
      - Getting Hands on with Ontologies: lesson/getting-hands-on.md
      - Leveraging ChatGPT for ontology curation: lesson/chatgpt-ontology-curation.md
      - Using Ontologies in Practice--LinkML can help: lesson/linkml-helps-with-ontology-use.md
      - Licensing Data and Software: lesson/licensing-data-and-software.md
      - Vocabularies for bioinformatics: lesson/vocabularies-for-bioinformatics.md
      - An Introduction to Synonyms in OBO Ontologies: lesson/synonyms.md
  - Lessons In Development:
      - Developing an Application Ontology: lesson/developing-application-ontologies.md
      - Ontology Development: lesson/ontology-development.md
      - Semantic Database Fundamentals: lesson/semantic-database-fundamentals.md
  - Tutorials:
      - Protege:
          - DL queries: tutorial/basic-dl-query.md
          - Disjointness: tutorial/disjointness.md
      - Ontology Pipelines - ODK, ROBOT, etc:
          - ROBOT Mini-Tutorial 1 - Convert, Extract and Template: tutorial/robot-tutorial-1.md
          - ROBOT Mini-Tutorial 2 - Annotate, Merge, Reason and Diff: tutorial/robot-tutorial-2.md
          - ROBOT Mini-Tutorial QC - Quality Control with report, verify and query: tutorial/robot-tutorial-qc.md
          - ROBOT - Generating SPARQL table reports: tutorial/sparql-report-robot.md
          - ODK - Adding SPARQL table reports: tutorial/sparql-report-odk.md
          - ODK - Getting started with your own repo: tutorial/setting-up-project-odk.md
          - ODK - 20 minute complete walk-through: tutorial/odk-tutorial-2.md
          - ODK - Adding custom Quality Check: tutorial/custom-qc.md
          - ODK - Managing imports: tutorial/managing-dynamic-imports-odk.md
          - ODK - Managing ontology releases: tutorial/managing-ontology-releases-odk.md
          - ODK - Migrating to ODK: tutorial/migrating-ontology-to-odk.md
          - ODK - Using the ODK Toolbox: tutorial/odk-toolbox.md
      - Templates:
          - Getting started with DOSDP templates: tutorial/dosdp-overview.md
          - DOSDP Templates Basic Tutorial: tutorial/dosdp-template.md
          - Introduction to Managing DOSDP Templates in ODK: tutorial/dosdp-odk.md
      - Git, GitHub and Collaborative Workflows:
          - GitHub Fundamentals for OBO Engineers: tutorial/github-fundamentals.md
          - GitHub Issue for OBO Engineers: tutorial/github-issues.md
          - Managing OBO ontology projects: tutorial/managing-ontology-project.md
          - Pull requests: tutorial/pull-requests.md
      - OntoGPT:
          - OntoGPT Introduction: tutorial/ontogpt.md
          - OntoGPT in Practice: tutorial/ontogpt-workshop.md
      - Dealing with Semantic Data:
          - From Tables to Linked Data: tutorial/linking-data.md
          - Standardizing Prefixes, CURIEs, and URIs with the `curies` package: tutorial/curies.md
          - Units of Measurement: tutorial/units.md
          - Basic SPARQL for OBO Engineers: tutorial/sparql.md
          - Using Large Language Models (LLMs) to generate SPARQL queries: tutorial/sparql-llm.md
          - Basic cypher on the Monarch Neo4j graph: tutorial/monarch-kg-neo4j-basics.md
      - Command line:
          - Basic introduction to CLI 1: tutorial/intro-cli-1.md
          - Basic introduction to CLI 2: tutorial/intro-cli-2.md
      - Mappings and SSSOM:
          - Basic Tutorial: tutorial/sssom-tutorial.md
          - Lexical Matching with OAK Lexmatch: tutorial/lexmatch-tutorial.md
          - Introduction to the SSSOM Toolkit: tutorial/sssom-toolkit.md
          - Curating Mappings with Biomappings: tutorial/biomappings.md
      - General Ontology Modelling:
          - Project Ontology Development: tutorial/project-ontology-development.md
          - Family History Knowledge Base (FHKB) tutorial: tutorial/fhkb.md
          - Using the Delphi method to bring domain knowledge into ontologies: tutorial/Delphi-method-ontology.md 
      - Exomiser:
          - Introduction to Exomiser: tutorial/exomiser-tutorial.md
      - Information Extraction:
          - Named Entity Recognition with Gilda: tutorial/named-entity-recognition.md
          - Named Entity Normalization: tutorial/named-entity-normalization.md
          - Named Entity Standardization: tutorial/named-entity-standardization.md
      - Biocuration with Claude Code:
          - Getting Started with Claude Code: tutorial/claude-code-getting-started.md
          - Exploring LinkML Models with Claude Code: tutorial/claude-code-linkml.md
          - Creating Slash Commands for API Lookups: tutorial/claude-code-slash-commands.md
          - Using MCPs for Bioinformatics Workflows: tutorial/claude-code-mcps.md
  - How-to guides:
      - General:
          - Maximising impact as an open science engineer: howto/open-science-engineer.md
          - Creating an ontology from scratch: howto/create-ontology-from-scratch.md
          - Create an ontology overview: howto/ontology-overview.md
          - Prettify Markdown Files: howto/prettify.md
          - Create Screenshot and paste into an issue: howto/screenshot.md
          - Set-up docker: howto/setup-docker.md
          - Create permanent identifiers with w3id.org: howto/create-permid-with-w3id.md
      - Protege:
          - Install Protégé: howto/install-protege.md
          - Setup Protege 5.5: howto/set-up-protege.md
          - Installing ELK in Protege: howto/installing-elk-in-protege.md
          - Setting up your ID range: howto/idrange.md
          - Editing in Protege: howto/edit-in-protege.md
          - Daily Workflow: howto/daily-curator-workflow.md
          - Edit in Protege: howto/edit-in-protege.md
          - Switching Ontologies in Protege: howto/switching-ontologies.md
          - Browsing and Searching: howto/protege-browse-search.md
          - Creating New Terms in Protege: howto/create-new-term.md
          - Obsoleting a Term: howto/obsolete-term.md
          - Merging Terms: howto/merge-terms.md
          - Adding Taxon Restrictions: howto/add-taxon-restrictions.md
          - Creating a new Slim (under construction): howto/add-new-slim.md
      - ODK:
          - Get set up for ODK-based ontology development: howto/setup-ontology-development-odk.md
          - Setting up the ODK: howto/odk-setup.md
          - Update to a newer ODK version: howto/odk-update.md
          - Creating a Repo with ODK: howto/odk-create-repo.md
          - Dealing with Large Ontologies: howto/deal-with-large-ontologies.md
          - Updating Imports with ODK: howto/update-import.md
          - Import ORCIDIO: howto/odk-add-orcidio-module.md
          - Running ODK with podman: howto/run-odk-with-podman.md
          - Migrate an existing ontology Repo to ODK: howto/odk-migrate-to-odk.md
      - Git and GitHub:
          - Make term requests to existing ontologies: howto/term-request.md
          - Clone a repository: howto/clone-mondo-repo.md
          - Fork an ontology for editing: howto/github-create-fork.md
          - Create a GitHub Pull Request: howto/github-create-pull-request.md
          - Change a pull request: howto/change-files-pull-request.md
          - Fix conflicts: howto/fixing-conflicts.md
          - Automate tasks with GitHub actions: howto/github-actions.md
          - Revert a commit: howto/revert-commit.md
          - Review a pull request: howto/review-pull-request.md
          - Respectful Collaboration: howto/respectful-collaboration.md
          - Add a Code of Conduct: howto/add-coc.md
      - Quality control:
          - Deploy a custom OBO-Dashboard: howto/deploy-custom-obo-dashboard.md
      - Command line:
          - How to filter a file based on another file: howto/filter-text-file.md
      - Mappings:
          - Are these two entities the same? A guide.: howto/are-two-entities-the-same.md
          - How to review disease mappings: howto/review-disease-mappings.md
  - Reference:
      - Tools: reference/glossary.md
      - Glossary of Terms: reference/glossary-of-terms.md
      - Frequently used ODK commands: reference/frequently-used-odk-commands.md
      - Protege Interface: reference/protege-interface.md
      - Protege FAQ: reference/protege-faq.md
      - LLMs for the Semantic Engineer: reference/llms.md
      - Formatting your ontology annotations correctly: reference/formatting-license.md
      - OBO-style term annotation: reference/go-style-annotation-property-practice.md
      - Ontology Matching:
          - Semantic ETL: reference/semantic-etl.md
      - Git:
          - Intro to GitHub: reference/github-intro.md
          - GitHub Desktop: reference/github-desktop.md
          - Git FAQ: reference/git-faq.md
      - Semantic Engineering Toolbox: reference/semantic-engineering-toolbox.md
      - Tables and Triples: reference/tables-and-triples.md
      - Reasoning: reference/reasoning.md
      - A day in the life of an ontology curator: reference/ontology-curator.md
      - Protege interface: reference/protege-interface.md
      - SPARQL:
          - SPARQL basics: reference/sparql-basics.md
          - SPARQL templates: reference/sparql-reference.md
      - Tools for Managing Issues: reference/managing-issues.md
      - Release Artefacts: reference/release-artefacts.md
      - Base Release: reference/base-specification.md
      - Synonym Properties: reference/synonyms-properties.md
      - Synonym Types: reference/synonyms-types.md
      - Synonym Validation: reference/synonym-validation.md
      - Monkeying around with OWL: reference/mungall-blog-radar.md
      - Ontology Development Kit (ODK): reference/odk.md
      - Troubleshooting ROBOT: reference/troublehooting-robot.md
      - Common Errors in GitHub actions: reference/gh-actions-errors.md
      - Other useful resources: reference/other-resources.md
      - Medical Ontology landscape: reference/medical-ontology-landscape.md
      - A reference guide to Wikidata: reference/wikidata.md
      - OBOOK Maturity Indicator: reference/obook-maturity-indicator.md
      - ChatGPT:
          - Leveraging ChatGPT for ontology curation: reference/chatgpt-prompts-for-ontology-development.md
      - Ontology User references: reference/ontology-user.md 
      - How XML Catalog files work: reference/catalog-xml.md
  - Explanations:
      - Introduction to Ontologies: explanation/intro-to-ontologies.md
      - Logical axiomatization of classes & use of reasoning: explanation/logical-axiomatization.md
      - Term Comments: explanation/term-comments.md
      - Introduction to Annotation Properties: explanation/annotation-properties.md
      - Writing good issues: explanation/writing-good-issues.md
      - Ontology Matching: explanation/ontology-matching.md
      - Which biomedical ontologies should we use?: explanation/which-ontology-to-use.md
      - OWL, OBO, JSON? Base, simple, full, basic? What should you use, and why?: explanation/owl-format-variants.md
      - What are taxon constraints?: explanation/taxon-constraints-explainer.md
      - The logical building blocks of OWL: explanation/owl-building-blocks.md
      - SubClassOf versus EquivalentTo: explanation/subClassOf-vs-equivalentTo.md
      - Existential restrictions: explanation/existential-restrictions.md

  - OBOOK Editors:
      - Getting started for OBOOK editors: getting-started-obook.md
      - How to add images: images/index.md
      - How to embed videos: howto/embed-video.md
      - New lesson template: config/template.md
      - Case studies for teaching: teaching/case-studies.md
  - Outreach:
      - Outreach materials: reference/outreach.md
repo_url: https://github.com/OBOAcademy/obook/
site_url: https://oboacademy.github.io/obook/
edit_uri: edit/master/docs/
